version: 2
registries:
  npm-github:
    type: npm-registry
    url: "https://registry.npmjs.org"
    token: "${{secrets.NPM_TOKEN}}"
    
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "daily"
#     reviewers:
#       - [GITHUB-USERNAME-GOES-HERE]
    labels:
      - dependencies
    allow:
      - dependency-name: "@volley/*"
    registries:
      - npm-github
